FROM jenkins/inbound-agent:alpine as jnlp

FROM alpine/helm

USER root

# Install jre 11
RUN apk -U add openjdk11-jre git

# Install kubectl latest version
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN adduser -h /home/jenkins -S jenkins 

USER jenkins

COPY --from=jnlp /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-agent
COPY --from=jnlp /usr/share/jenkins/agent.jar /usr/share/jenkins/agent.jar

ENTRYPOINT ["/usr/local/bin/jenkins-agent"]
